export const LOAD_MASTER_SUCCESS = "LOAD_MASTER_SUCCESS";
export const LOAD_MASTER_ERROR = "LOAD_MASTER_ERROR";


export const LOAD_DETAIL_SUCCESS = "LOAD_DETAIL_SUCCESS";
export const LOAD_DETAIL_ERROR = "LOAD_DETAIL_ERROR";

export const SAVE_DETAIL_REQUEST = "SAVE_DETAIL_REQUEST";
export const SAVE_DETAIL_SUCCESS = "SAVE_DETAIL_SUCCESS";
export const SAVE_DETAIL_ERROR = "SAVE_DETAIL_ERROR";

export const LOAD_DEVICE_ACTIONS_SUCCESS = "LOAD_DEVICE_ACTIONS_SUCCESS";
export const LOAD_DEVICE_ACTIONS_ERROR = "LOAD_DEVICE_ACTIONS_ERROR";
